# Generated by Django 4.2.7 on 2023-11-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cernyrobin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUserProfile',
            fields=[
                ('clicks', models.IntegerField(default=0)),
                ('clicks_auto', models.IntegerField(default=0)),
                ('clicks_mult', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
