# Generated by Django 4.2.7 on 2023-11-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cernyrobin_app', '0003_alter_anonymoususerprofile_clicks_mult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususerprofile',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='anonymoususerprofile',
            name='clicks_auto',
        ),
        migrations.RemoveField(
            model_name='anonymoususerprofile',
            name='clicks_mult',
        ),
        migrations.RemoveField(
            model_name='anonymoususerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='clicks_auto',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='clicks_mult',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
