# Generated by Django 4.2.7 on 2023-11-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cernyrobin_app', '0004_remove_anonymoususerprofile_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='callme',
            field=models.CharField(default='{"phone_number": ""}', max_length=100),
        ),
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='robin_clicker',
            field=models.CharField(default='{"clicks": 0, "clicks_auto": 0, "clicks_mult": 1}', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='callme',
            field=models.CharField(default='{"phone_number": ""}', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='robin_clicker',
            field=models.CharField(default='{"clicks": 0, "clicks_auto": 0, "clicks_mult": 1}', max_length=100),
        ),
    ]
