# Generated by Django 5.0.1 on 2024-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cernyrobin_app', '0006_anonymoususerprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
