# Generated by Django 5.0.1 on 2024-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cernyrobin_app', '0007_anonymoususerprofile_email_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususerprofile',
            name='email_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
