# Generated by Django 4.2.7 on 2023-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kafka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=10)),
                ('transcript', models.CharField(max_length=999999)),
                ('answers', models.CharField(max_length=99999)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('last_generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
