# Generated by Django 4.2.7 on 2023-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='last_generated',
            field=models.DateTimeField(),
        ),
    ]
