# Generated by Django 4.2.7 on 2023-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_system_last_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafka',
            name='video_url',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
