# Generated by Django 4.2.7 on 2023-12-05 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_job_id_alter_job_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
