# Generated by Django 4.2.7 on 2023-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_job_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.FloatField(default=0),
        ),
    ]
