# Generated by Django 4.2.7 on 2023-12-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_kafka_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafka',
            name='video_info',
            field=models.JSONField(default={}),
        ),
    ]
