# Generated by Django 4.2.7 on 2023-12-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_kafka_video_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafka',
            name='video_info',
            field=models.JSONField(default=dict),
        ),
    ]
