# Generated by Django 4.2.7 on 2023-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_kafka_video_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='last_generated',
            field=models.IntegerField(default=0),
        ),
    ]
