# Generated by Django 4.2.7 on 2023-12-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_kafka_timestamp_alter_system_last_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kafka',
            name='answers',
            field=models.CharField(max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='kafka',
            name='language',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kafka',
            name='timestamp',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kafka',
            name='transcript',
            field=models.CharField(max_length=999999, null=True),
        ),
    ]
