# Generated by Django 5.0.1 on 2024-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_kafka_answers_alter_kafka_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafka',
            name='custom_answers',
            field=models.JSONField(default=str, null=True),
        ),
    ]
