# Generated by Django 4.2.7 on 2023-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_system_last_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('video_url', models.CharField(max_length=70)),
                ('percent_completed', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
