# Generated by Django 5.0.1 on 2024-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_kafka_custom_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafka',
            name='summary',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
