# Generated by Django 4.2.7 on 2023-12-04 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_job_chunks_completed_job_total_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
