# Generated by Django 5.0.1 on 2024-03-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_kafka_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafka',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
