# Generated by Django 5.0.1 on 2024-03-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_kafka_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafka',
            name='comments',
            field=models.JSONField(default=str, null=True),
        ),
    ]
