# Generated by Django 4.2.7 on 2023-12-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('ad_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=30)),
                ('name', models.CharField(default='ad', max_length=30)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('image_link', models.CharField(max_length=100)),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
